---
title: "Exploratory Data Analysis"
author: "Ursula Podosenin"
date: "2025-02-14"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}

# Load dataset
data(mtcars)

# Check structure
str(mtcars)

# View first few rows
head(mtcars)

# Check for missing values
sum(is.na(mtcars))
```

```{r}

# Convert 'cyl', 'vs', 'am', 'gear', and 'carb' to factors
mtcars$cyl  <- as.factor(mtcars$cyl)
mtcars$vs   <- as.factor(mtcars$vs)
mtcars$am   <- as.factor(mtcars$am)
mtcars$gear <- as.factor(mtcars$gear)
mtcars$carb <- as.factor(mtcars$carb)

# Check structure again
str(mtcars)
```

```{r}

summary(mtcars)
```

```{r}

hist(mtcars$mpg, breaks=10, col="skyblue", main="Distribution of MPG", xlab="Miles Per Gallon")
```

```{r}

boxplot(mpg ~ cyl, data=mtcars, col=c("red", "blue", "green"),
        main="MPG by Number of Cylinders", xlab="Cylinders", ylab="MPG")
```

```{r}

plot(density(mtcars$hp), main="Density Plot of Horsepower", col="darkblue", lwd=2)
```

```{r}

cor_matrix <- cor(mtcars[, sapply(mtcars, is.numeric)])
print(cor_matrix)
```

```{r}

install.packages("corrplot")
library(corrplot)
corrplot(cor_matrix, method="color", addCoef.col="black", tl.col="black")
```

```{r}

plot(mtcars$wt, mtcars$mpg, main="MPG vs. Car Weight",
     xlab="Weight (1000 lbs)", ylab="Miles Per Gallon", col="blue", pch=19)
abline(lm(mpg ~ wt, data=mtcars), col="red", lwd=2)  # Add regression line
```

```{r}

boxplot(mpg ~ am, data=mtcars, col=c("orange", "purple"),
        main="MPG by Transmission Type", xlab="Transmission (0 = Automatic, 1 = Manual)", ylab="MPG")
```

